#!/bin/bash

# root directory
export RD_ROOT_DIR=/home/ubuntu/.rmd

# lua environment
export LUA_EXE=$RD_ROOT_DIR/bin/lua
export LUA_INIT=@$RD_ROOT_DIR/src/lua_init.lua

# server address
DAEMON_FILE=$RD_ROOT_DIR/src/rd_server.lua
DAEMON="$LUA_EXE $DAEMON_FILE"

function start_server () {
    # Client Mode. Client connect IP/PORT
    local ip=`ifconfig eno1|awk -F' ' '/inet /{print $2}'`
    export RD_SERVER_IP=${ip%% *}
    export RD_SERVER_PORT=30130

    # put rd command in standard path
    export PATH=$PATH:$RD_ROOT_DIR/script
    nohup $DAEMON >/dev/null 2>/dev/null &
}

daemon_cnt=`ps -ef | grep "$DAEMON" |cut -d' ' -f4 | wc -w`
if [ "$daemon_cnt" -le 1 ]; then
    start_server
fi
